research_task:
  description: >
    Conduza uma pesquisa completa sobre {topic} com base no nível de público {audience_level}.
    Certifique-se de encontrar qualquer informação interessante, relevante e atual (publicada no final de 2024 e início de 2025).
  expected_output: >
    Um relatório de pesquisa completo sobre {topic} com informações relevantes que podem inspirar conteúdo educacional posteriormente direcionado a {audience_level}. 
    O relatório de pesquisa também deve incluir referências às fontes que você usou para criar o conteúdo.
  agent: researcher

seo_task:
  description: >
    Conduza uma pesquisa completa sobre {topic} com afim de encontrar palavras-chave que mais performam em SEO.
    Certifique-se de encontrar qualquer informação interessante, relevante e atual (publicada no final de 2024 e início de 2025).
  expected_output: >
    Um relatório de palavras-chave relevantes sobre {topic} que podem engajar melhor os conteúdos criados no blog. 
    O relatório de pesquisa também deve incluir referências às fontes que você usou.
  agent: marketer

planning_task:
  description: >
    Revise o conteúdo que você recebeu e crie um plano para uma peça de conteúdo educacional incrível e abrangente que seja direcionada a {audience_level}.
    O plano deve ser altamente detalhado e abrangente.
  expected_output: >
    Um plano detalhado para uma peça de conteúdo educacional que é direcionada a {audience_level}.
    O plano deve ser uma série de seções, cada seção com um subtítulo, objetivo de alto nível, por que é importante e fontes referenciadas.
  agent: planner
